export const calendarEvents = [
  { date: '2026-01-01', title: "New Year's Day", type: 'public', region: 'All India', details: 'The first day of the Gregorian calendar year.' },
  { date: '2026-01-13', title: 'Lohri', type: 'festival', region: 'Punjab, Haryana, North India', details: 'Winter harvest festival celebrated with bonfires, traditional songs, and community gatherings.' },
  { date: '2026-01-14', title: 'Makar Sankranti', type: 'festival', region: 'All India', details: "Harvest festival marking the Sun's transition into Makara, celebrated under different regional names." },
  { date: '2026-01-14', title: 'Pongal', type: 'festival', region: 'Tamil Nadu', details: 'Tamil harvest festival celebrating the Sun, new harvest, cattle, and prosperity.' },
  { date: '2026-01-15', title: 'Thai Pongal', type: 'festival', region: 'Tamil Nadu', details: 'Main day of the Pongal festival dedicated to thanksgiving to the Sun.' },
  { date: '2026-01-16', title: 'Mattu Pongal', type: 'festival', region: 'Tamil Nadu', details: 'Pongal day dedicated to cattle, with traditional decorations and celebrations.' },
  { date: '2026-01-17', title: 'Kaanum Pongal', type: 'festival', region: 'Tamil Nadu', details: 'Day of family visits, outings, and community gatherings following the Pongal celebrations.' },
  { date: '2026-01-26', title: 'Republic Day', type: 'public', region: 'All India', details: 'National holiday marking the adoption of the Constitution of India.' },
  { date: '2026-02-01', title: 'Vasant Panchami', type: 'festival', region: 'All India', details: 'Festival welcoming spring and associated with Goddess Saraswati, learning, and knowledge.' },
  { date: '2026-02-15', title: 'Maha Shivaratri', type: 'festival', region: 'All India', details: 'Night dedicated to Lord Shiva, observed with prayers, fasting, and temple visits.' },
  { date: '2026-02-19', title: 'Shivaji Jayanti', type: 'community', region: 'Maharashtra', details: 'Birth anniversary of Chhatrapati Shivaji Maharaj.' },
  { date: '2026-03-04', title: 'Holi', type: 'festival', region: 'All India', details: 'Festival of colors welcoming spring and celebrating joy, community, and renewal.' },
  { date: '2026-03-19', title: 'Ugadi / Gudi Padwa', type: 'festival', region: 'Karnataka, Andhra Pradesh, Telangana, Maharashtra', details: 'Regional New Year celebrations with traditional food, rituals, and new beginnings.' },
  { date: '2026-03-20', title: 'Cheti Chand', type: 'festival', region: 'Sindhi communities', details: 'Sindhi New Year and celebration of Jhulelal.' },
  { date: '2026-03-21', title: 'Eid ul-Fitr', type: 'festival', region: 'All India', details: 'Islamic festival marking the completion of Ramadan, observed with prayers, charity, and family gatherings.' },
  { date: '2026-03-26', title: 'Ram Navami', type: 'festival', region: 'All India', details: 'Celebration of the birth of Lord Rama.' },
  { date: '2026-03-31', title: 'Mahavir Jayanti', type: 'festival', region: 'Jain communities', details: 'Birth anniversary of Lord Mahavira, the 24th Tirthankara.' },
  { date: '2026-04-03', title: 'Good Friday', type: 'public', region: 'All India', details: 'Christian holy day commemorating the crucifixion of Jesus Christ.' },
  { date: '2026-04-14', title: 'Ambedkar Jayanti', type: 'public', region: 'All India', details: 'Birth anniversary of Dr. B. R. Ambedkar.' },
  { date: '2026-04-14', title: 'Tamil New Year', type: 'festival', region: 'Tamil Nadu', details: 'Tamil New Year, traditionally known as Puthandu, marking the beginning of the Tamil calendar year.' },
  { date: '2026-04-14', title: 'Vaisakhi', type: 'festival', region: 'Punjab and North India', details: 'Punjabi harvest festival and important Sikh observance.' },
  { date: '2026-04-20', title: 'Eid ul-Adha', type: 'festival', region: 'All India', details: "Islamic festival commemorating Ibrahim's devotion and observed with prayers, charity, and family gatherings." },
  { date: '2026-05-01', title: 'Labour Day', type: 'public', region: 'Many Indian states', details: 'Day recognizing workers and the labor movement.' },
  { date: '2026-05-01', title: 'Maharashtra Day', type: 'public', region: 'Maharashtra', details: 'State foundation day commemorating the formation of Maharashtra.' },
  { date: '2026-05-01', title: 'Buddha Purnima', type: 'festival', region: 'All India', details: 'Buddhist observance commemorating the birth, enlightenment, and passing of Gautama Buddha.' },
  { date: '2026-06-21', title: 'International Yoga Day', type: 'community', region: 'All India', details: 'Annual celebration promoting yoga, health, wellness, and wellbeing.' },
  { date: '2026-06-26', title: 'Muharram', type: 'festival', region: 'All India', details: 'Important Islamic observance marking the beginning of the Islamic month of Muharram.' },
  { date: '2026-07-16', title: 'Rath Yatra', type: 'festival', region: 'Odisha and other parts of India', details: 'Major Hindu chariot festival associated with Lord Jagannath.' },
  { date: '2026-07-29', title: 'Guru Purnima', type: 'festival', region: 'All India', details: 'Day honoring spiritual teachers, mentors, and gurus.' },
  { date: '2026-08-15', title: 'Independence Day', type: 'public', region: 'All India', details: "National holiday commemorating India's independence." },
  { date: '2026-08-26', title: 'Janmashtami', type: 'festival', region: 'All India', details: 'Celebration of the birth of Lord Krishna.' },
  { date: '2026-08-28', title: 'Onam', type: 'festival', region: 'Kerala', details: 'Kerala harvest festival known for flower carpets, traditional feasts, cultural celebrations, and boat races.' },
  { date: '2026-08-28', title: 'Raksha Bandhan', type: 'festival', region: 'All India', details: 'Festival celebrating the bond between brothers and sisters through the tying of Rakhi.' },
  { date: '2026-09-04', title: 'Janmashtami', type: 'festival', region: 'Some Indian regions', details: 'Regional observance of the birth of Lord Krishna based on local calendars.' },
  { date: '2026-09-14', title: 'Vinayagar Chaturthi', type: 'festival', region: 'Maharashtra, Tamil Nadu, Karnataka, Andhra Pradesh', details: 'Festival welcoming Lord Ganesha with prayers, public celebrations, and immersion ceremonies.' },
  { date: '2026-09-21', title: 'Ganesh Visarjan', type: 'festival', region: 'Maharashtra, Tamil Nadu, Karnataka, Andhra Pradesh', details: 'Traditional immersion ceremony marking the conclusion of many Ganesha Chaturthi celebrations.' },
  { date: '2026-10-02', title: 'Gandhi Jayanti', type: 'public', region: 'All India', details: 'National holiday commemorating the birth of Mahatma Gandhi.' },
  { date: '2026-10-20', title: 'Dussehra', type: 'festival', region: 'All India', details: 'Festival celebrating the victory of good over evil, with different regional traditions.' },
  { date: '2026-10-22', title: 'Valmiki Jayanti', type: 'festival', region: 'All India', details: 'Birth anniversary of Maharishi Valmiki, traditionally associated with the Ramayana.' },
  { date: '2026-10-29', title: 'Karwa Chauth', type: 'festival', region: 'North India', details: 'Traditional festival observed primarily by married women with fasting and prayers for their spouses.' },
  { date: '2026-11-08', title: 'Diwali', type: 'festival', region: 'All India', details: 'Festival of lights celebrated with lamps, prayers, sweets, family gatherings, and cultural traditions.' },
  { date: '2026-11-09', title: 'Govardhan Puja', type: 'festival', region: 'North and Central India', details: 'Hindu festival associated with Lord Krishna and the worship of Govardhan Hill.' },
  { date: '2026-11-10', title: 'Bhai Dooj', type: 'festival', region: 'All India', details: 'Festival celebrating the bond between brothers and sisters.' },
  { date: '2026-11-24', title: 'Guru Nanak Jayanti', type: 'festival', region: 'Sikh communities', details: 'Birth anniversary of Guru Nanak Dev Ji, the first Sikh Guru.' },
  { date: '2026-12-25', title: 'Christmas Day', type: 'public', region: 'All India', details: 'Christian holiday celebrating the birth of Jesus Christ.' }
]
