function NoteList({ loading, error, visibleNotes, notes, pinnedCount, view, search, dateRange, sortOrder, onViewChange, onSearchChange, onDateChange, onSortChange, editingId, editingText, updatingId, deletingId, onEditTextChange, onBeginEdit, onCancelEdit, onSaveEdit, onTogglePin, onDelete }) {
  return (
    <section className="notes-stage">
      <div className="notes-toolbar"><label className="search-field" htmlFor="search"><span>⌕</span><input id="search" value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search notes" /></label><div className="view-tabs"><button className={view === 'all' ? 'active' : ''} type="button" onClick={() => onViewChange('all')}>All <span>{notes.length}</span></button><button className={view === 'pinned' ? 'active' : ''} type="button" onClick={() => onViewChange('pinned')}>Pinned <span>{pinnedCount}</span></button></div></div>
      <div className="date-toolbar"><label>Period <select value={dateRange} onChange={(event) => onDateChange(event.target.value)}><option value="all">All time</option><option value="week">This week</option><option value="month">This month</option><option value="year">This year</option></select></label><label>Sort <select value={sortOrder} onChange={(event) => onSortChange(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label><span className="result-count">{visibleNotes.length} shown</span></div>
      {error && <p className="error">{error}</p>}
      <div className="notes-list">{loading ? <p className="empty">Gathering your notes...</p> : visibleNotes.length === 0 ? <p className="empty">{search ? 'No notes match that search.' : view === 'pinned' ? 'Nothing pinned yet.' : 'Your archive is waiting for its first note.'}</p> : visibleNotes.map((note, index) => <article className="note" key={note.id}><div className="note-index">{String(index + 1).padStart(2, '0')}</div><div className="note-content">{editingId === note.id ? <textarea className="edit-input" value={editingText} onChange={(event) => onEditTextChange(event.target.value)} autoFocus rows="3" /> : <p>{note.text}</p>}<time>{note.updatedAt ? 'Edited ' : ''}{new Date(note.updatedAt || note.createdAt).toLocaleString()}</time></div><div className="note-actions">{editingId === note.id ? <><button className="action-button save-action" type="button" onClick={() => onSaveEdit(note.id)} disabled={updatingId === note.id}>{updatingId === note.id ? 'Saving...' : 'Save'}</button><button className="action-button" type="button" onClick={onCancelEdit}>Cancel</button></> : <><button className={`pin-button ${note.pinned ? 'pinned' : ''}`} type="button" onClick={() => onTogglePin(note)} disabled={updatingId === note.id} aria-label={note.pinned ? 'Unpin note' : 'Pin note'}>{note.pinned ? '★' : '☆'}</button><button className="action-button" type="button" onClick={() => onBeginEdit(note)}>Edit</button><button className="action-button delete-button" type="button" onClick={() => onDelete(note.id)} disabled={deletingId === note.id}>{deletingId === note.id ? 'Deleting...' : 'Delete'}</button></>}</div></article>)}</div>
    </section>
  )
}

export default NoteList
